MyBlog.WebUI/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Business.Abstract;
using MyBlog.DataAccess.ViewModels;
using MyBlog.Entities.Concrete;

namespace MyBlog.WebUI.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService _postService;
        private readonly ICategoryService _categoryService;
        private readonly ICommentService _commentService;


        public PostController(
            ICommentService commentService,
            ICategoryService categoryService,
            IPostService postService
            )
        {
            _commentService = commentService;
            _categoryService = categoryService;
            _postService = postService;
        }

        public IActionResult Index(int? categoryId = null)
        {
            var viewModel = new PostsViewModel();
            if (categoryId == null)
                viewModel.Posts = _postService.GetPosts();
            else
                viewModel.Posts = _postService.GetPosts(p => p.CategoryId == categoryId);

            return View(viewModel);
        }

        public IActionResult Add()
        {
            var viewModel = new PostViewModel();
            viewModel.Categories = _categoryService.GetCategoriesForCategoryComboBox();

            return View(viewModel);
        }
        [HttpPost]

        public IActionResult Add(PostViewModel viewModel)
        {

            if (_postService.AddPost(viewModel.PostDto))
            {
                
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        public IActionResult Update(int postId)
        {
            var viewModel = new PostViewModel();
            viewModel.PostDto = _postService.GetPost(x => x.Id == postId);
            viewModel.Categories = _categoryService.GetCategoriesForCategoryComboBox();
            
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Update(PostViewModel viewModel)
        {

           if (_postService.UpdatePost(viewModel.PostDto))
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        
       
        public IActionResult Delete(int id)
        {
            if (_postService.DeletePost(id))
            {
                return RedirectToAction("Index");
            }
            return View();
        }


        public IActionResult Detail(int id)
        {
            var viewModel = new PostViewModel();
            viewModel.PostDto = _postService.GetPost(p => p.Id == id);
            return View(viewModel);
        }

        public IActionResult AddComment(CommentsViewModel viewModel)
        {
            _commentService.AddComment(viewModel.CommentDto);
            
            return RedirectToAction("Detail", new { id = viewModel.CommentDto.PostId });
        }

        public IActionResult DeleteComment(int id)
        {
            if (_commentService.DeleteComment(id))
            {
                return RedirectToAction("Profile","Account");
            }
            return View();
        }
    }
}

MyBlog.WebUI/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using MyBlog.Business.Abstract;
using MyBlog.DataAccess.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBlog.WebUI.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {

        private readonly ICategoryService _categoryService;

        public CategoryListViewComponent(
            ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {
            var model = new CategoriesViewModel();
            model.Categories = _categoryService.GetList();
            return View(model);
        }
    }
}

MyBlog.WebUI/ViewComponents/CommentViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using MyBlog.Business.Abstract;
using MyBlog.DataAccess.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBlog.WebUI.ViewComponents
{
    public class CommentViewComponent : ViewComponent
    {
        private readonly ICommentService _commentService;
        public CommentViewComponent(ICommentService commentService)
        {
            _commentService = commentService;
        }

        public ViewViewComponentResult Invoke(int postId)
        {
            var model = new CommentsViewModel();
            model.Comments = _commentService.GetListWithUserInformation(p=>p.PostId == postId);
            model.PostId = postId;
            return View(model);
        }
    }
}

MyBlog.WebUI/Views/Post/Add.cshtml
@model MyBlog.DataAccess.ViewModels.PostViewModel
@{
    ViewData["Title"] = "Add";
}


<div class="container">
    <div class="col-md-12">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PostDto.CategoryId" class="control-label">Category</label>
                    <select asp-for="PostDto.CategoryId" asp-items="Model.Categories" class="form-control"></select>
                    <span asp-validation-for="PostDto.CategoryId" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PostDto.Title" class="control-label"></label>
                    <input asp-for="PostDto.Title" class="form-control" />
                    <span asp-validation-for="PostDto.Title" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PostDto.Summary" class="control-label"></label>
                    <textarea asp-for="PostDto.Summary" class="form-control"></textarea>
                    <span asp-validation-for="PostDto.Summary" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PostDto.Content" class="control-label"></label>
                    <textarea asp-for="PostDto.Content" class="form-control"></textarea>
                    <span asp-validation-for="PostDto.Content" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PostDto.Picture" class="control-label">Picture URL </label>
                    <input asp-for="PostDto.Picture" class="form-control" />
                    <span asp-validation-for="PostDto.Picture" class="text-danger"></span>
                </div>
            </div>
            <div class="row col-md-6">

                <div class="form-group">
                    <input type="submit" value="Kaydet" class="btn btn-primary" style="float:right" />
                </div>
            </div>

        </form>
    </div>
</div>

MyBlog.WebUI/Views/Post/Detail.cshtml
@model MyBlog.DataAccess.ViewModels.PostViewModel
@{
    ViewData["Title"] = "Detail";
}

<div class="container">

    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryList")
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="card text-center">
                    <div class="card-header">
                        @Model.PostDto.Title
                    </div>
                    <div class="card-body">
                        <img src="@Model.PostDto.Picture" width="100%" />
                        <p class="card-text">@Model.PostDto.Content</p>
                        @{
                            var timeSpan = (DateTime.Now - Model.PostDto.CreationDate);
                            int day = timeSpan.Days;
                            int hours = timeSpan.Hours;
                            int minutes = timeSpan.Minutes;

                        }

                        @day gün - @hours saat - @minutes dakika önce eklendi.
                    </div>
                    <hr />
                    <div class="text-left" style="margin-left:20px;">
                        <h3>Yorumlar</h3>
                        @await Component.InvokeAsync("Comment", new { postId = Model.PostDto.Id })

                    </div>
                </div>
            </div>

        </div>
    </div>

</div>

MyBlog.WebUI/Views/Post/Index.cshtml
@model MyBlog.DataAccess.ViewModels.PostsViewModel
@{
    ViewData["Title"] = "Index";
}

<div class="container">

    <div class="row">
        @*<div class="col-md-0">
            @await Component.InvokeAsync("CategoryList")
        </div>*@

        
            <div>
                <button type="button">@TempData["Message"]</button>
            </div>
      
        @if (Model.Posts.Count == 0)
        {
            <span class="alert-danger" style="margin-top:30px;">Bu kategoriye ait herhangi bir gönderi bulunmamaktadır.</span>
        }
        else
        {
            @foreach (var item in Model.Posts)
            {
                <div class="card" style="width: 18rem;">
                    <img src="@item.Picture" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">@item.Title</h5>
                        <p class="card-text">@item.Summary</p>
                        <a asp-controller="Post" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-success">Devamını okuyun</a>
                    </div>
                </div>
            }
        }


    </div>
</div>

MyBlog.WebUI/Views/Post/Update.cshtml
@model MyBlog.DataAccess.ViewModels.PostViewModel
@{
    ViewData["Title"] = "Update";
}
<div class="container">
    <div class="col-md-12">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PostDto.CategoryId" class="control-label">Category</label>
                    <select asp-for="PostDto.CategoryId" asp-items="Model.Categories" class="form-control"></select>
                    <span asp-validation-for="PostDto.CategoryId" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PostDto.Title" class="control-label"></label>
                    <input asp-for="PostDto.Title" class="form-control" />
                    <span asp-validation-for="PostDto.Title" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PostDto.Summary" class="control-label"></label>
                    <textarea asp-for="PostDto.Summary" class="form-control"></textarea>
                    <span asp-validation-for="PostDto.Summary" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PostDto.Content" class="control-label"></label>
                    <textarea asp-for="PostDto.Content" class="form-control"></textarea>
                    <span asp-validation-for="PostDto.Content" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PostDto.Picture" class="control-label">Picture URL </label>
                    <input asp-for="PostDto.Picture" class="form-control" />
                    <span asp-validation-for="PostDto.Picture" class="text-danger"></span>
                </div>
            </div>
            <div class="row col-md-6">

                <div class="form-group">
                    <input type="hidden" asp-for="PostDto.Id" />
                    <input type="submit" value="Güncelle" class="btn btn-primary" style="float:left" />
                    <a class="btn btn-danger" asp-action="Delete" asp-controller="Post" asp-route-id="@Model.PostDto.Id">Sil</a>
                </div>
            </div>

        </form>
    </div>
</div>